# Platform
TARGET_BOARD_PLATFORM := mt6739

# Architecture
TARGET_ARCH := arm64
TARGET_ARCH_VARIANT := armv8-a-neon
TARGET_CPU_ABI := armeabi-v7a
TARGET_CPU_ABI2 := armeabi
TARGET_CPU_SMP := true
TARGET_CPU_VARIANT := cortex-a53

# Bootloader
TARGET_NO_BOOTLOADER := true
TARGET_BOOTLOADER_BOARD_NAME := MT6739WW

# Kernel
TARGET_PREBUILT_KERNEL := device/samsung/a013f/kernel
BOARD_KERNEL_CMDLINE := bootopt=64S3,32S1,32S1
BOARD_KERNEL_BASE := 0x40000000
BOARD_KERNEL_PAGESIZE := 2048
BOARD_KERNEL_SEPARATED_DT := true
BOARD_MKBOOTIMG_ARGS := --dt device/samsung/a013f/dt.img --ramdisk_offset 0x05000000 --kernel_offset 0x00008000 --tags_offset 0x04000000

# Partitions
BOARD_BOOTIMAGE_PARTITION_SIZE := 33554432
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 33554432
BOARD_SYSTEMIMAGE_PARTITION_SIZE := 2365587456
BOARD_CACHEIMAGE_PARTITION_SIZE := 131072000
BOARD_USERDATAIMAGE_PARTITION_SIZE := 12445417472
BOARD_FLASH_BLOCK_SIZE := 131072

# Recovery
TARGET_RECOVERY_PIXEL_FORMAT := "BGRA_8888"
TARGET_USERIMAGES_USE_EXT4 := true
BOARD_HAS_LARGE_FILESYSTEM := true
BOARD_USE_CUSTOM_RECOVERY_FONT := \"roboto_15x24.h\"
BOARD_SUPPRESS_EMMC_WIPE := true

# TWRP
HAVE_SELINUX := true
DEVICE_RESOLUTION := 720x1480
TW_IGNORE_MAJOR_AXIS_0 := true
RECOVERY_GRAPHICS_USE_LINELENGTH := true
BOARD_HAS_NO_REAL_SDCARD := true
#TW_DEFAULT_EXTERNAL_STORAGE := # это смотрим как у похожего аппарата
TW_INTERNAL_STORAGE_PATH := /internal_sd
TW_INTERNAL_STORAGE_MOUNT_POINT := internal_sd
TW_EXTERNAL_STORAGE_PATH := /external_sd
TW_EXTERNAL_STORAGE_MOUNT_POINT := external_sd

# USB Mounting
#TARGET_USE_CUSTOM_LUN_FILE_PATH := ????
